### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by Dave-Huang666** [kw81634dr/BMD101-plotter#1]
Dear Author

    This BMD101 plotter program is very useful for me. I highly appreciate your contribution. I have a few questions regarding it:

    Firstly, if I did not mistaken it, the hardware should be EPS32. Could you please tell me how I should connect the BMB101 module to the EPS32 board?

    Secondly, based on your program, I would like to expand it by converting the hexadecimal data to binary, and output the binary data with the EPS32. May I ask if it is possible? How fast can EPS output these 1s and 0s. 

    Thank you very much.

Best regards
Qi Huang

**Comment by kw81634dr** [comment]
Hi Qi,
BMD101 uses a UART interface to communicate with the microcontroller, so
either UART0, UART1, or UART2 is good, personally, I prefer UART2 for easy
access.

Converting value between hexadecimal & binary is possible on many
platforms, but it's been a while I can barely recall this portion in my
code.
For the speed for conversion, I never tested it, it sounds like something
related to performance, I believe you could find the info on the internet.

BTW, this is not an issue, I'm happy to discuss technical topics, feel free
to email me instead of opening an issue, thank you.

Dave-Huang666 ***@***.***> 於 2022年1月23日 週日 上午5:25寫道：

**Comment by kw81634dr** [comment]
closing issue
